apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik
data:
  traefik.toml: |
    defaultEntryPoints = ["http", "https"]
    debug = true
    logLevel = "INFO"
    InsecureSkipVerify = true

    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
        
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]

    [kubernetes]
    watch=true

    [accessLog]
    [metrics]
      [metrics.prometheus]
      buckets=[0.1,0.3,1.2,5.0]
      entryPoint = "traefik"

    [ping]
    entryPoint = "http"

    [consul]
    endpoint = "consul.consul.svc.cluster.local:8500"
    watch = true
    prefix = "traefik"

    [acme]
    email = "clustercamp@gmail.com"
    storage = "traefik/acme/account"
    onDemand=true
    onHostRule=true
    acmeLogging = true
    overrideCertificates = true
    entryPoint = "https"

      [acme.dnsChallenge]
      provider = "gcloud"
  