apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-conf
  namespace: kube-system
data:
  traefik.toml: |
    defaultEntryPoints = ["http", "https"]
    debug = true
    logLevel = "INFO"
    InsecureSkipVerify = true

    [entryPoints]
      [entryPoints.http]
      address = ":80"
      compress = true
        
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]

    [kubernetes]
    [accessLog]
    [metrics]
      [metrics.prometheus]
      buckets=[0.1,0.3,1.2,5.0]
      entryPoint = "traefik"
    [ping]
    entryPoint = "http"

    [acme]
    email = "clustercamp@gmail.com"
    storage = "/etc/traefik/acme.json"
    onDemand=true
    onHostRule=true
    acmeLogging = true
    entryPoint = "https"

      [acme.dnsChallenge]
      provider = "gcloud"
  