---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: traefik-acme
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nvme
  resources:
    requests:
      storage: 100Mi
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:v1.7
        name: traefik-ingress-lb
        env:
        - name: GCE_PROJECT
          value: clustercamp
        - name: GCE_SERVICE_ACCOUNT_FILE
          value: /secret/key.json
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /etc/traefik
          name: acme
        - mountPath: /secret
          name: google-cloud-key
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: admin
          containerPort: 8080
        args:
        - --api
        - --kubernetes
        - --configfile=/config/traefik.toml
      volumes:
        - name: config
          configMap:
            name: traefik-conf
        - name: acme
          persistentVolumeClaim:
            claimName: traefik-acme
        - name: google-cloud-key
          secret:
            secretName: cloud-dns-key
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: k8s-app
                  operator: In
                  values:
                  - traefik-ingress-lb
              topologyKey: kubernetes.io/hostname
---
kind: Service
apiVersion: v1
metadata:
  name: traefik
  namespace: kube-system
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 443
      name: https
    - protocol: TCP
      port: 8080
      name: admin
  loadBalancerIP: 192.168.1.100
  type: LoadBalancer