apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-ingress
  namespace: network
  labels:
    k8s-app: traefik-ingress
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: traefik-ingress
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress
    spec:
      serviceAccountName: traefik-ingress
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:v1.7.14
        name: traefik-ingress
        env:
        - name: GCE_PROJECT
          value: clustercamp
        - name: GCE_SERVICE_ACCOUNT_FILE
          value: /secret/key.json
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /secret
          name: google-cloud-key
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: admin
          containerPort: 8080
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO
        - --configfile=/config/traefik.toml
      volumes:
        - name: config
          configMap:
            name: traefik-config
        - name: google-cloud-key
          secret:
            secretName: cloud-dns-key
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values: ["node1", "node2", "node3"]
---
kind: Service
apiVersion: v1
metadata:
  name: traefik
  namespace: network
spec:
  selector:
    k8s-app: traefik-ingress
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 443
      name: https
    - protocol: TCP
      port: 8080
      name: admin
  loadBalancerIP: 192.168.1.100
  type: LoadBalancer