apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"] 
  resources: ["ingresses"] 
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        # image: lazypower/external-dns:v0.5.12-22-g3d9f2d36-dirty
        image: dockercamp/external-dns:v0.5.16-15-gbc36ee90-dirty
        imagePullPolicy: Always
        volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
        args:
        - --source=service
        - --source=ingress
        - --publish-internal-services
        - --domain-filter=cluster.camp
        - --provider=google
        - --google-project=clustercamp
        - --policy=upsert-only
        - --registry=txt
        - --txt-prefix=txt-
        - --txt-owner-id=clustercamp
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
      volumes:
        - name: google-cloud-key
          secret:
            secretName: cloud-dns-key