# config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: mysql
data:
  default_auth: |
    [mysqld]
    default_authentication_plugin= mysql_native_password
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-storage
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2G
---
kind: Pod
apiVersion: v1
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql/mysql-server:latest-aarch64
      imagePullPolicy: Always
      ports:
        - containerPort: 3306
          name: mysql
      env:
      - name: MYSQL_ROOT_PASSWORD # use only for debugging
        value: "root123456"
      - name: MYSQL_DATABASE
        value: "spring"
      - name: MYSQL_USER
        value: "spring"
      - name: MYSQL_PASSWORD
        value: "spring1234"
      volumeMounts:
      - name: mysql-config-volume ## specify volume name
        mountPath: /etc/mysql/conf.d/default_auth.cnf ## path to mount file
        subPath: default_auth ## name of config
      - name: mysql-persistent-storage
        mountPath: /var/lib/mysql
  volumes:
    - name: mysql-config-volume ## volume name
      configMap:
        name: mysql-config
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-storage
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
      name: mysql
  clusterIP: None
  selector:
    app: mysql